name: theraplib_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  get_storage: ^2.0.3
  dio: ^4.0.6
  retrofit: ^3.3.1
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  ionicons: ^0.2.1
  liquid_pull_to_refresh: ^3.0.1
  diacritic: ^0.1.3
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.17.0
  flutter_svg: ^1.1.6
  flutter_native_splash: ^2.2.0+1
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  flutter_image_compress: ^1.1.3
  http_parser: ^4.0.2
  mime: ^1.0.4
  path: ^1.8.2
  path_provider: ^2.0.11
  badges: ^2.0.3
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  retrofit_generator: ^4.2.0
  flutter_launcher_icons: ^0.11.0

# flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: '#FFFFFF'
  remove_alpha_ios: true


# flutter_native_splash
flutter_native_splash:
  color: '#FFFFFF'
  image: assets/images/logo.png
  color_dark: '#FFFFFF'
  image_dark: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: '#FFFFFF'
    image_dark: assets/images/logo.png
    icon_background_color_dark: '#FFFFFF'


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
